# Generated by Django 5.0.6 on 2024-07-01 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteruni', '0002_remove_inventario_id_categoria_inventario_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id_kit', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('nombre_kit', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='id_kit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='masteruni.kit'),
        ),
    ]
