# Generated by Django 5.0.6 on 2024-07-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masteruni', '0005_alter_inventario_id_kit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kit',
        ),
    ]
