# Generated by Django 5.0.6 on 2024-07-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteruni', '0007_remove_inventario_id_kit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id_kit', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_kit', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='id_kit',
            field=models.IntegerField(default='0'),
        ),
    ]
