# Generated by Django 5.0.6 on 2024-07-03 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteruni', '0008_kit_inventario_id_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='id_kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masteruni.kit'),
        ),
    ]
